/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v2': typeof V2Route
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v2': typeof V2Route
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/v2': typeof V2Route
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/v2' | '/api/public/lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/v2' | '/api/public/lead'
  id: '__root__' | '/' | '/v2' | '/api/public/lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V2Route: typeof V2Route
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V2Route: V2Route,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
